# -*- coding: utf-8 -*-
"""Untitled83.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17sq5KIKzY3QEXQbCzU1uWgWnuZtR55YD
"""

import streamlit as st
import pandas as pd
import joblib

modelo = joblib.load("modelo_accidentalidad_envigado.pkl")

st.title("Predicción de gravedad de accidentes de tránsito en Envigado")

st.write("Ingrese las características del accidente para estimar su nivel de gravedad.")

mes = st.selectbox("Mes", list(range(1, 13)))
dia_semana = st.selectbox("Día de la semana", list(range(1, 8)))
hora = st.selectbox("Hora", list(range(0, 24)))
resultado_beodez = st.number_input("Resultado de beodez", min_value=0, step=1)
clase_accidente = st.text_input("Clase de accidente")
causa = st.text_input("Causa")
barrio = st.text_input("Barrio")

if st.button("Predecir"):
    entrada = pd.DataFrame([{
        "mes": mes,
        "dia_semana": dia_semana,
        "hora": hora,
        "resultado_beodez": resultado_beodez,
        "clase_accidente": clase_accidente,
        "causa": causa,
        "barrio": barrio
    }])

    prediccion = modelo.predict(entrada)[0]

    st.success(f"La gravedad estimada del accidente es: {prediccion}")